// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Recommends relevant city services based on user input.
 *
 * - recommendService - A function that recommends city services.
 * - RecommendServiceInput - The input type for the recommendService function.
 * - RecommendServiceOutput - The return type for the recommendService function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendServiceInputSchema = z.object({
  description: z
    .string()
    .describe('The description of the issue or need from the citizen.'),
});

export type RecommendServiceInput = z.infer<typeof RecommendServiceInputSchema>;

const RecommendServiceOutputSchema = z.object({
  serviceRecommendations: z
    .array(z.string())
    .describe('An array of recommended city services.'),
});

export type RecommendServiceOutput = z.infer<typeof RecommendServiceOutputSchema>;

export async function recommendService(input: RecommendServiceInput): Promise<RecommendServiceOutput> {
  return recommendServiceFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendServicePrompt',
  input: {schema: RecommendServiceInputSchema},
  output: {schema: RecommendServiceOutputSchema},
  prompt: `Based on the following description of an issue or need, recommend relevant city services:

Description: {{{description}}}

Return an array of service recommendations.`,
});

const recommendServiceFlow = ai.defineFlow(
  {
    name: 'recommendServiceFlow',
    inputSchema: RecommendServiceInputSchema,
    outputSchema: RecommendServiceOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
